SimpleDeligate
BaseWebDev/HT_8 pull request #2
Opened 2018-05-04 21:35 UTC by SermusAnton

2018-05-06 06:49 UTC, ilpoli requested changes

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +    class CustomList<T> : IEnumerable<T[]>, IList<T[]>,IEquatable<T[]> where T : struct {
зачем ограничение на struct?

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +        public OnRemoving<int> onRemovingAt;
зачем оно? есть же remove, и такого достаточно думаю

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +        public bool IsReadOnly => ((IList<T[]>)internalList).IsReadOnly;
просто false можно

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/SimpleListChangedEventArgs.cs
> +        public SimpleListChangedEventArgs() : this(default(T[])) {
в чем смысл этого пустого конструктора?

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +            return ((IList<T[]>)internalList).IndexOf(item);
а зачем везде (IList<T[]>) ?

2018-05-06 06:49 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +            Updated(new SimpleListChangedEventArgs<T>(arr));
Не правда на add не происходит update. add - на добавления записи, update на изменений записи, например через индексатор. По крайней мере, такая идея была.

2018-05-06 07:01 UTC, ilpoli requested changes

2018-05-06 07:01 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +            return Equals(arg1, arg2);
точно не так )

2018-05-06 07:01 UTC, ilpoli commented on SimpleListArray/ListArray.cs
> +            Updated(new SimpleListChangedEventArgs<T>(arr));
Похоже у тебя Update означает что лист изменился, в этом случае ok

2018-05-07 13:40 UTC, SermusAnton commented
Исправил

2018-05-11 09:42 UTC, SermusAnton commented
Исправил

2018-06-06 11:08 UTC, ilpoli approved these changes

2018-06-06 13:50 UTC, merged